apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels: 
    app: narayani
spec:
 replicas: 3
 selector:
   matchLabels:
     app: narayani
 template:
   metadata:
     labels: 
       app: narayani
   spec:
     containers:
     - name: myappcontainer
       image: naveen0101/narayani:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
